// Généré depuis Questions_Jury_RNCP_CDA.xlsx — Banque de questions (102 questions, jury RNCP37873 CDA).
// Ne pas éditer à la main : régénérer depuis la source Excel.

export const QUESTIONS = [
  {
    "num": 1,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Environnement de dev",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Décrivez votre environnement de développement : OS, IDE, langages, outils. Comment l'avez-vous mis en place ?",
    "reponse": "Réponse structurée : OS de travail, IDE (VS Code, IntelliJ…) et extensions clés, gestionnaire de versions du langage (nvm, pyenv), gestionnaire de paquets (npm, composer, pip), outils annexes (Postman/Insomnia, DBeaver, Git). Le candidat doit montrer un environnement reproductible et documenté.",
    "vigilance": "Relancer : « un nouvel arrivant peut-il tout réinstaller en suivant votre doc ? » On cherche la reproductibilité, pas une liste d'outils."
  },
  {
    "num": 2,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Environnement de dev",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Pourquoi avoir choisi ce framework / cette librairie plutôt qu'un autre ? Sur quels critères ?",
    "reponse": "Critères objectifs attendus : maturité et communauté, courbe d'apprentissage, écosystème, performance, sécurité/maintenance, adéquation au besoin, contexte de l'équipe/entreprise. Éviter « parce qu'on nous l'a imposé en formation » sans recul.",
    "vigilance": "Piège : réponse « c'est le plus connu ». Creuser un vrai arbitrage (au moins une alternative écartée et pourquoi)."
  },
  {
    "num": 3,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Environnement de dev",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Comment un nouveau développeur installe et lance votre projet ? Qu'y a-t-il dans votre README ?",
    "reponse": "Procédure claire : prérequis, clonage, installation des dépendances, copie du .env.example, variables à renseigner, commande de lancement, seed de la BDD. Un README (ou Notion) à jour est attendu.",
    "vigilance": "Bon signe : « make install » ou « docker compose up » unique. Vérifier que le .env n'est PAS versionné."
  },
  {
    "num": 4,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Conteneurisation",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce que Docker vous apporte concrètement ? Différence entre une image et un conteneur ?",
    "reponse": "Image = modèle immuable (recette, couches figées) ; conteneur = instance en exécution d'une image. Apports : environnement identique dev/prod, isolation, reproductibilité, onboarding rapide, pas de « ça marche sur ma machine ».",
    "vigilance": "Relance classique : différence Docker vs machine virtuelle (Docker partage le noyau de l'hôte, plus léger ; la VM embarque un OS complet)."
  },
  {
    "num": 5,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Conteneurisation",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "À quoi sert votre docker-compose ? Décrivez vos services.",
    "reponse": "Orchestration multi-conteneurs (app, base de données, reverse proxy…) via un seul fichier : réseaux, volumes pour la persistance, variables d'environnement, dépendances entre services. Permet de monter toute la stack d'une commande.",
    "vigilance": "Vérifier la compréhension des volumes (persistance des données de la BDD) et des réseaux internes."
  },
  {
    "num": 6,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Interfaces utilisateur",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Comment avez-vous construit votre charte graphique ? Que contient-elle ?",
    "reponse": "Palette de couleurs, typographies, logo, iconographie, composants réutilisables, espacements, états (hover, focus, disabled). Justification par l'identité du projet et la cible utilisateur.",
    "vigilance": "Faire le lien avec l'accessibilité : les couleurs choisies passent-elles les contrastes ?"
  },
  {
    "num": 7,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Interfaces utilisateur",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment garantissez-vous l'accessibilité (RGAA) ? Citez des critères concrets.",
    "reponse": "Contraste texte/fond ≥ 4.5:1 (texte normal), navigation clavier, labels de formulaires, textes alternatifs des images, structure sémantique (balises HTML, landmarks), tailles de zones cliquables, ne pas véhiculer l'info uniquement par la couleur. Référentiel : RGAA / WCAG.",
    "vigilance": "Le RNCP insiste sur le RGAA. Demander un exemple mesuré (outil : Lighthouse, axe, WAVE, contrast checker)."
  },
  {
    "num": 8,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Interfaces utilisateur",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Différence entre un wireframe et une maquette ? Quels outils avez-vous utilisés ?",
    "reponse": "Wireframe = zoning basse fidélité (structure, hiérarchie de l'information, sans style). Maquette = haute fidélité (couleurs, typo, contenu réel), proche du rendu final. Outils : Figma, Adobe XD, Penpot…",
    "vigilance": "Bonus : maquette + prototype cliquable pour tester les enchaînements d'écrans."
  },
  {
    "num": 9,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Interfaces utilisateur",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Justifiez vos choix d'UX / d'ergonomie. Avez-vous testé auprès d'utilisateurs ?",
    "reponse": "Décisions guidées par le parcours utilisateur : réduction du nombre de clics, feedback visuel, cohérence, hiérarchie visuelle, prévention des erreurs. Idéalement, retours utilisateurs / itérations.",
    "vigilance": "Attendu : un raisonnement centré utilisateur, pas des goûts personnels."
  },
  {
    "num": 10,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Interfaces utilisateur",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Quelles technologies front-end avez-vous utilisées et pourquoi ce framework ?",
    "reponse": "HTML/CSS/JS + framework (React, Vue, Angular…). Justifier : réactivité, composants réutilisables, gestion d'état, écosystème. Distinguer SPA vs rendu serveur si pertinent.",
    "vigilance": "Relance : « qu'est-ce qu'un composant ? comment gérez-vous l'état ? »"
  },
  {
    "num": 11,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Interfaces utilisateur",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment gérez-vous le responsive ? Avez-vous une approche mobile-first ?",
    "reponse": "Media queries, unités relatives (%, rem, vw), flexbox/grid, breakpoints. Mobile-first = concevoir d'abord pour petit écran puis enrichir. Tester sur plusieurs résolutions.",
    "vigilance": "Vérifier que le responsive est bien dans le CODE et pas seulement sur les maquettes."
  },
  {
    "num": 12,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Interfaces utilisateur",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment validez-vous les champs côté interface ? Est-ce suffisant pour la sécurité ?",
    "reponse": "Validation front = confort UX et retour immédiat (formats, champs requis, longueurs). NON suffisant : elle est contournable (désactivation JS, appel API direct). La validation serveur reste obligatoire.",
    "vigilance": "Question piège essentielle : si le candidat dit « la validation front suffit », c'est un signal fort à creuser."
  },
  {
    "num": 13,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Interfaces utilisateur",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Qu'est-ce qu'une faille XSS ? Comment la prévenez-vous côté front ?",
    "reponse": "XSS = injection de script malveillant exécuté dans le navigateur d'un autre utilisateur. Prévention : échappement/encodage des sorties, ne pas injecter de HTML brut (éviter innerHTML/dangerouslySetInnerHTML), Content-Security-Policy, sanitization des entrées. Les frameworks modernes échappent par défaut.",
    "vigilance": "Distinguer XSS stockée / réfléchie / DOM-based si le candidat est à l'aise."
  },
  {
    "num": 14,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Interfaces utilisateur",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment gérez-vous l'affichage conditionnel selon le rôle de l'utilisateur ?",
    "reponse": "Masquage des éléments UI selon le rôle (rendu conditionnel). MAIS c'est cosmétique : la vraie protection est côté serveur. Cacher un bouton n'empêche pas d'appeler la route.",
    "vigilance": "Le point clé : l'UI ne fait pas la sécurité. Vérifier qu'ils protègent aussi la route back."
  },
  {
    "num": 15,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Composants métier",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Décrivez l'architecture de vos composants métier. Comment votre code est-il découpé ?",
    "reponse": "Découpage modulaire : séparation contrôleurs / services (logique métier) / accès données ; responsabilités isolées, modules réutilisables, faible couplage / forte cohésion.",
    "vigilance": "Faire décrire le trajet d'une requête à travers les couches."
  },
  {
    "num": 16,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Composants métier",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Quels design patterns avez-vous implémentés ? Donnez un exemple concret dans VOTRE code.",
    "reponse": "Un ou deux patterns réellement utilisés : Repository (accès données), Singleton (connexion), Factory (création d'objets), Observer, Strategy, MVC/MVVM. L'important : montrer où et pourquoi, pas réciter une définition.",
    "vigilance": "Piège fréquent : citer un pattern sans savoir l'expliquer. Demander « où dans votre code ? »"
  },
  {
    "num": 17,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Composants métier",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Expliquez le pattern Repository et ce qu'il vous apporte.",
    "reponse": "Couche d'abstraction entre la logique métier et la source de données. Le métier manipule des objets sans savoir si c'est SQL, NoSQL, une API… Avantages : testabilité (mock du repository), maintenabilité, changement de source facilité.",
    "vigilance": "Relancer avec un autre pattern cité dans le dossier pour vérifier la maîtrise réelle."
  },
  {
    "num": 18,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Composants métier",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Comment isolez-vous vos règles métier pour les faire évoluer sans casser le reste ?",
    "reponse": "Règles centralisées dans une couche service dédiée, découplées des contrôleurs et de la BDD ; injection de dépendances ; tests unitaires garantissant la non-régression. Une règle change à un seul endroit.",
    "vigilance": "Bon indicateur de séniorité : parle de tests de non-régression et de couplage faible."
  },
  {
    "num": 19,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Composants métier",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Comment sécurisez-vous vos composants métier (permissions, validation) ?",
    "reponse": "Validation systématique des entrées côté serveur, contrôle des permissions à chaque action, principe de moindre privilège, jamais de confiance dans les données du client.",
    "vigilance": "Enchaîner sur la vérification des droits sur une ressource précise (voir IDOR)."
  },
  {
    "num": 20,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Composants métier",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Comment protégez-vous vos routes sensibles ? Différence authentification / autorisation ?",
    "reponse": "Authentification = vérifier QUI est l'utilisateur (login, token). Autorisation = vérifier ce qu'il a le DROIT de faire (rôles/permissions). Middleware d'auth + contrôle de rôle sur chaque route sensible.",
    "vigilance": "Question quasi certaine à l'oral. Réponse floue = alerte."
  },
  {
    "num": 21,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Composants métier",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Pourquoi valider les données côté serveur alors qu'elles le sont déjà côté client ?",
    "reponse": "Le client est contrôlé par l'utilisateur : validation JS contournable, appels directs à l'API (Postman, curl). Le serveur est le seul point de confiance : il doit tout revalider. Défense en profondeur.",
    "vigilance": "Réponse de référence attendue mot pour mot presque. Insister si évasif."
  },
  {
    "num": 22,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Composants métier",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment gérez-vous les erreurs back-end ? Que ne faut-il jamais exposer à l'utilisateur ?",
    "reponse": "Gestion centralisée des erreurs, messages génériques côté client, codes HTTP appropriés, logs détaillés côté serveur uniquement. Ne jamais exposer : stack trace, requêtes SQL, chemins de fichiers, versions, secrets.",
    "vigilance": "Un message d'erreur trop bavard = fuite d'information exploitable."
  },
  {
    "num": 23,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Composants métier",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Comment vérifiez-vous qu'un utilisateur a le droit d'accéder à une ressource précise (ex : la commande n°42) ?",
    "reponse": "Contrôle d'appartenance côté serveur : vérifier que la ressource appartient bien à l'utilisateur authentifié, pas seulement qu'il est connecté. Sinon faille IDOR (Insecure Direct Object Reference).",
    "vigilance": "Excellent discriminant. Beaucoup vérifient l'auth mais pas l'appartenance → IDOR."
  },
  {
    "num": 24,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Gestion de projet",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Quelle méthodologie de gestion de projet avez-vous utilisée et pourquoi ?",
    "reponse": "Scrum, Kanban, Shape Up, cycle en V… Justifier selon taille d'équipe et projet : itératif/agile pour l'adaptabilité, Kanban pour le flux, cycle en V pour un cadrage figé. Expliquer sprints, backlog, rituels si Scrum.",
    "vigilance": "Demander comment la méthode a été VÉCUE, pas la théorie du cours."
  },
  {
    "num": 25,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Gestion de projet",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Comment avez-vous planifié et suivi vos tâches ?",
    "reponse": "Backlog priorisé, découpage en tâches, outil de suivi (Trello, Jira, Notion, GitHub Projects), estimation, suivi d'avancement. Éventuellement diagramme de Gantt.",
    "vigilance": "Vérifier l'usage réel de l'outil (captures dans le dossier)."
  },
  {
    "num": 26,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Gestion de projet",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Quel workflow Git avez-vous choisi (Gitflow, trunk-based) ? Expliquez-le.",
    "reponse": "Gitflow : branches main/develop/feature/release/hotfix. Trunk-based : petites branches courtes fusionnées vite dans main. Justifier selon la taille d'équipe. Décrire le cheminement d'une feature jusqu'à main.",
    "vigilance": "Relancer : différence merge / rebase ; rôle des pull requests."
  },
  {
    "num": 27,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Gestion de projet",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment gérez-vous les secrets (.env, .gitignore) ? Que faire si un .env a été poussé sur GitHub ?",
    "reponse": "Secrets dans .env non versionné, .env.example fourni, .gitignore configuré, variables d'environnement en prod. Si fuite : considérer les secrets compromis → les RÉVOQUER et régénérer (les retirer de l'historique ne suffit pas).",
    "vigilance": "Piège : « je l'ai supprimé du repo ». Non — un secret exposé doit être changé, il est dans l'historique/caches."
  },
  {
    "num": 28,
    "bloc": "Bloc 1 — Dev application sécurisée",
    "categorie": "Gestion de projet",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Différence entre git merge et git rebase ? Qu'est-ce qu'une pull request ?",
    "reponse": "Merge : fusionne en conservant l'historique (commit de merge). Rebase : réapplique les commits sur une nouvelle base (historique linéaire, réécrit). PR = demande de fusion soumise à revue de code avant intégration.",
    "vigilance": "Ne pas rebase des branches partagées publiquement (réécriture d'historique)."
  },
  {
    "num": 29,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Analyse des besoins",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Comment avez-vous analysé les besoins du client / des utilisateurs ?",
    "reponse": "Recueil (entretiens, cahier des charges), formalisation en fonctionnalités, priorisation (MoSCoW), user stories, critères d'acceptation. Distinguer besoin exprimé et besoin réel.",
    "vigilance": "Relancer sur la validation des besoins avec les parties prenantes."
  },
  {
    "num": 30,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Analyse des besoins",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Différence entre un besoin fonctionnel et un besoin non fonctionnel ?",
    "reponse": "Fonctionnel = ce que le système doit faire (créer un compte, passer commande). Non fonctionnel = comment (performance, sécurité, accessibilité, disponibilité, scalabilité, maintenabilité).",
    "vigilance": "Demander un exemple de chaque tiré du projet."
  },
  {
    "num": 31,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Analyse des besoins",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Qu'est-ce qu'un cahier des charges ? Qu'y trouve-t-on ?",
    "reponse": "Document de référence : contexte, objectifs, périmètre, besoins fonctionnels et non fonctionnels, contraintes techniques, livrables, délais. Sert de contrat entre client et équipe.",
    "vigilance": "Lien avec les spécifications techniques détaillées."
  },
  {
    "num": 32,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Analyse des besoins",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce qu'une user story ? Un diagramme de cas d'utilisation ?",
    "reponse": "User story : « En tant que [rôle], je veux [action] afin de [bénéfice] » + critères d'acceptation. Cas d'utilisation (UML) : acteurs et interactions avec le système. Formalise le besoin fonctionnel.",
    "vigilance": "Vérifier la présence de diagrammes UML dans le dossier."
  },
  {
    "num": 33,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Architecture logicielle",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Décrivez votre architecture multicouche. Quelles sont vos couches et leurs rôles ?",
    "reponse": "Présentation (UI/contrôleurs) → métier/services (règles) → accès données (repository/ORM) → BDD. Chaque couche ne communique qu'avec la couche adjacente. Le RNCP exige explicitement une architecture multicouche.",
    "vigilance": "Point central du Bloc 2. Faire dessiner/décrire le flux d'une requête de bout en bout."
  },
  {
    "num": 34,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Architecture logicielle",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Pourquoi une architecture en couches ? Quels avantages ?",
    "reponse": "Séparation des responsabilités, maintenabilité, testabilité, réutilisabilité, remplacement d'une couche sans impacter les autres, travail en équipe facilité.",
    "vigilance": "Relancer : inconvénients ? (verbosité, latence entre couches)."
  },
  {
    "num": 35,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Architecture logicielle",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Quels aspects de sécurité avez-vous intégrés dans votre architecture (référentiel ANSSI) ?",
    "reponse": "Défense en profondeur, moindre privilège, validation à chaque couche, chiffrement en transit (HTTPS) et au repos, séparation des environnements, gestion des secrets, journalisation. Référence aux recommandations ANSSI (attendu par le RNCP).",
    "vigilance": "Le RNCP cite explicitement l'ANSSI. Bonus si le candidat connaît le guide d'hygiène ANSSI."
  },
  {
    "num": 36,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Architecture / Interopérabilité",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce qu'une API REST ? Citez des verbes HTTP et des codes de statut.",
    "reponse": "REST = style d'architecture basé sur des ressources, sans état, via HTTP. Verbes : GET (lire), POST (créer), PUT/PATCH (modifier), DELETE (supprimer). Codes : 200, 201, 400, 401, 403, 404, 500. Échange souvent en JSON.",
    "vigilance": "Relance : différence PUT vs PATCH ; que veut dire « stateless » ?"
  },
  {
    "num": 37,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Architecture / Interopérabilité",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Différence entre REST, GraphQL et SOAP ? Formats d'échange (JSON, XML) ?",
    "reponse": "REST : ressources + verbes HTTP, JSON, simple. GraphQL : une requête, le client choisit les champs (évite over/under-fetching). SOAP : protocole strict, XML, verbeux, contrat WSDL. Choix selon besoin.",
    "vigilance": "Demander lequel ils ont utilisé et pourquoi."
  },
  {
    "num": 38,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Organisation en couches",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce que le principe de séparation des responsabilités (Separation of Concerns) ?",
    "reponse": "Chaque module/couche a une responsabilité unique et bien définie. Réduit le couplage, améliore la lisibilité et la maintenance. Lié au principe S de SOLID (Single Responsibility).",
    "vigilance": "Enchaîner sur SOLID / DRY / KISS."
  },
  {
    "num": 39,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Modèles de données",
    "demo": "Démo 1",
    "demoKey": "demo1",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Présentez votre MCD. Expliquez une relation entre deux entités et sa cardinalité.",
    "reponse": "MCD = entités, associations, cardinalités (1,1 / 1,n / n,n). Le candidat doit lire son propre schéma : ex. « un client passe 0..n commandes, une commande appartient à 1 client ».",
    "vigilance": "Vérifier la gestion des relations n..n (table de jonction dans le MPD)."
  },
  {
    "num": 40,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Modèles de données",
    "demo": "Optionnel",
    "demoKey": "optionnel",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Différence entre MCD, MLD et MPD ?",
    "reponse": "MCD : conceptuel, métier, indépendant de la techno (Merise). MLD : logique, traduit en tables/clés, choix relationnel. MPD : physique, types SQL concrets, index, contraintes, spécifique au SGBD.",
    "vigilance": "Bonus : passage MCD → MLD (association n..n devient une table)."
  },
  {
    "num": 41,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Modèles de données",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce que la normalisation ? Expliquez la 1re, 2e et 3e forme normale.",
    "reponse": "Réduire la redondance et les anomalies. 1NF : valeurs atomiques. 2NF : 1NF + dépendance de toute la clé. 3NF : 2NF + pas de dépendance transitive entre attributs non-clés. Objectif : cohérence des données.",
    "vigilance": "Question technique classique. Un exemple concret de leur schéma renforce la crédibilité."
  },
  {
    "num": 42,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Sécurité BDD",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Comment hachez-vous les mots de passe ? Pourquoi pas un chiffrement ?",
    "reponse": "Hachage à sens unique + sel (bcrypt, Argon2, scrypt). On ne veut PAS pouvoir déchiffrer un mot de passe. Le sel empêche les rainbow tables ; l'algo est lent volontairement (résistance au brute force).",
    "vigilance": "Piège majeur : « je chiffre les mots de passe » est FAUX. On les hache. Insister."
  },
  {
    "num": 43,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Sécurité BDD",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Différence entre hachage, chiffrement et encodage ?",
    "reponse": "Hachage : à sens unique, irréversible (mots de passe, intégrité). Chiffrement : réversible avec une clé (confidentialité). Encodage : transformation réversible SANS secret (Base64), ce n'est PAS de la sécurité.",
    "vigilance": "Beaucoup confondent Base64 et chiffrement. Bon discriminant."
  },
  {
    "num": 44,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Sécurité BDD",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Qu'est-ce qu'une injection SQL et comment la prévenez-vous ?",
    "reponse": "Injection de code SQL via une entrée non filtrée pour altérer une requête. Prévention : requêtes préparées / paramétrées, ORM, échappement, validation des entrées, moindre privilège du compte BDD. Ne jamais concaténer des entrées utilisateur.",
    "vigilance": "Question quasi systématique. Demander un exemple de requête vulnérable vs sécurisée."
  },
  {
    "num": 45,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Sécurité BDD",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment sécurisez-vous l'accès à la base de données ?",
    "reponse": "Compte applicatif à privilèges minimaux (pas de root), mot de passe fort en variable d'env, accès réseau restreint, pas d'accès direct exposé, chiffrement des connexions, sauvegardes.",
    "vigilance": "Principe de moindre privilège = fil rouge du RNCP côté sécurité."
  },
  {
    "num": 46,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Optimisation BDD",
    "demo": "Optionnel",
    "demoKey": "optionnel",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Qu'est-ce qu'un index ? Quand faut-il en créer et quel est le coût ?",
    "reponse": "Structure accélérant les recherches sur une/des colonnes (souvent B-tree). À poser sur colonnes filtrées/jointes fréquemment. Coût : ralentit les écritures et occupe de l'espace. Ne pas sur-indexer.",
    "vigilance": "Question de niveau avancé, valorisante. Optionnel dans la checklist."
  },
  {
    "num": 47,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Accès aux données",
    "demo": "Démo 3",
    "demoKey": "demo3",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce qu'un ORM ? Avantages et inconvénients ?",
    "reponse": "Object-Relational Mapping : mappe des objets vers des tables, on manipule des objets plutôt que du SQL. Avantages : productivité, portabilité, sécurité (requêtes paramétrées). Inconvénients : abstraction coûteuse, requêtes complexes moins optimisées, problème N+1.",
    "vigilance": "Nommer l'ORM utilisé (Prisma, Sequelize, Doctrine, Eloquent, SQLAlchemy) et l'illustrer."
  },
  {
    "num": 48,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Accès aux données",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Quand privilégier du SQL natif plutôt que l'ORM ?",
    "reponse": "Requêtes complexes, jointures lourdes, optimisation fine de performance, opérations en masse. L'ORM couvre le CRUD courant ; le SQL natif reprend la main sur les cas critiques.",
    "vigilance": "Vérifier qu'ils savent aussi écrire du SQL, pas seulement appeler l'ORM."
  },
  {
    "num": 49,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Accès aux données",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Qu'est-ce qu'une transaction ? Expliquez les propriétés ACID.",
    "reponse": "Transaction = ensemble d'opérations tout-ou-rien. ACID : Atomicité (tout ou rien), Cohérence (contraintes respectées), Isolation (transactions concurrentes ne s'interfèrent pas), Durabilité (persistance après commit).",
    "vigilance": "Demander un cas concret du projet (ex : virement, commande + stock)."
  },
  {
    "num": 50,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Accès aux données",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce que le pattern DAO / Repository dans votre stratégie d'accès aux données ?",
    "reponse": "Couche dédiée qui centralise les opérations d'accès aux données et isole le reste de l'application du détail de la persistance. Facilite tests, maintenance et changement de source.",
    "vigilance": "Recouvre le pattern Repository du Bloc 1 : cohérence attendue."
  },
  {
    "num": 51,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Accès aux données NoSQL",
    "demo": "Optionnel",
    "demoKey": "optionnel",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Avez-vous utilisé du NoSQL ? Quand est-ce pertinent par rapport au SQL ?",
    "reponse": "NoSQL (MongoDB, Redis…) : données non/peu structurées, forte volumétrie, scalabilité horizontale, schéma flexible, cache. SQL : données relationnelles, intégrité forte, transactions. Choix selon le besoin, pas la mode.",
    "vigilance": "Le RNCP mentionne SQL ET NoSQL. Même sans usage, savoir quand l'un ou l'autre."
  },
  {
    "num": 52,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Accès aux données",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Qu'est-ce que le problème N+1 et comment l'éviter ?",
    "reponse": "Une requête initiale + N requêtes pour charger les relations de chaque résultat → explosion du nombre de requêtes. Solution : eager loading / jointures (JOIN, include, with), chargement anticipé des relations.",
    "vigilance": "Discriminant de séniorité. Lié au lazy vs eager loading."
  },
  {
    "num": 53,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Documentation technique",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Comment documentez-vous votre API ?",
    "reponse": "Swagger / OpenAPI : endpoints, paramètres, corps, réponses, codes d'erreur, authentification, exemples. Documentation vivante et testable. Sinon Postman collection / README structuré.",
    "vigilance": "Si le projet est une API, cette doc est explicitement demandée dans la checklist."
  },
  {
    "num": 54,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Documentation technique",
    "demo": "Démo 2",
    "demoKey": "demo2",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Comment documentez-vous votre code source ?",
    "reponse": "Commentaires pertinents (le pourquoi, pas le quoi), conventions de nommage claires, docstrings/JSDoc, README, éventuellement génération auto de doc. Un code lisible se documente en partie lui-même.",
    "vigilance": "Attention au sur-commentaire : commenter l'intention, pas paraphraser le code."
  },
  {
    "num": 55,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Stratégie de déploiement",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Différence entre les environnements dev, test (staging) et prod ?",
    "reponse": "Dev : local, itération rapide. Test/staging : iso-prod pour valider avant mise en ligne. Prod : environnement réel des utilisateurs. Données, configs et secrets distincts pour chaque.",
    "vigilance": "Vérifier qu'ils ne testent pas en prod et que les configs sont séparées."
  },
  {
    "num": 56,
    "bloc": "Bloc 2 — Application en couches",
    "categorie": "Stratégie de déploiement",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Comment sécurisez-vous votre déploiement (HTTPS, SSH, moindre privilège) ?",
    "reponse": "HTTPS/TLS en prod (certificat, ex : Let's Encrypt), accès SSH par clé (pas mot de passe), désactivation du login root, pare-feu, moindre privilège, variables d'environnement pour les secrets, mises à jour.",
    "vigilance": "Fil rouge sécurité du RNCP. Demander comment les secrets arrivent en prod (pas dans le code)."
  },
  {
    "num": 57,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Tests",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Quelle est votre stratégie de tests ? Connaissez-vous la pyramide des tests ?",
    "reponse": "Pyramide : beaucoup d'unitaires (rapides, isolés), moins d'intégration, peu d'e2e (lents, coûteux). Stratégie priorisée par le risque métier. Décrire ce qui est réellement testé dans le projet.",
    "vigilance": "Relancer : « pourquoi peu de tests e2e ? » (coût, lenteur, fragilité)."
  },
  {
    "num": 58,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Tests",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Différence entre test unitaire, test d'intégration et test end-to-end ?",
    "reponse": "Unitaire : une fonction isolée (avec mocks). Intégration : plusieurs composants ensemble (ex : service + BDD). E2E : parcours utilisateur complet dans un navigateur, du front au back.",
    "vigilance": "Demander un exemple de chaque dans le projet."
  },
  {
    "num": 59,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Tests",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Quels outils et frameworks de tests avez-vous utilisés ?",
    "reponse": "Selon la stack : Jest/Vitest, PHPUnit, PyTest, JUnit (unitaire/intégration) ; Cypress/Playwright/Selenium (e2e) ; Postman/Newman (API). Nommer et justifier.",
    "vigilance": "S'assurer qu'ils savent LANCER les tests et lire un rapport."
  },
  {
    "num": 60,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Tests",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce qu'un mock, une fixture, un stub ? Comment isolez-vous vos données de test ?",
    "reponse": "Mock : objet simulé qui imite un comportement. Stub : renvoie des valeurs prédéfinies. Fixture : jeu de données de test connu. Isolation : base de test dédiée, données réinitialisées entre les tests, mocks des dépendances externes.",
    "vigilance": "Point checklist explicite : données de test isolées. Vérifier qu'ils ne testent pas sur la vraie base."
  },
  {
    "num": 61,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Tests",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce que le taux de couverture (coverage) ? Un fort taux garantit-il la qualité ?",
    "reponse": "Pourcentage de code exécuté par les tests. NON suffisant : on peut couvrir sans vraiment vérifier le comportement (assertions faibles). C'est un indicateur, pas une preuve de qualité. Privilégier les chemins critiques.",
    "vigilance": "Point checklist : analyse de couverture ET limites. Le recul compte autant que le chiffre."
  },
  {
    "num": 62,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Tests",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Donnez un exemple concret de bug détecté par vos tests et comment vous l'avez corrigé.",
    "reponse": "Cas réel attendu : un test a échoué, diagnostic, correction, test de non-régression ajouté. Montre que les tests servent vraiment.",
    "vigilance": "Point checklist explicite. Une histoire vécue vaut mieux qu'une théorie."
  },
  {
    "num": 63,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Tests",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Comment justifiez-vous votre périmètre de test au regard des risques métier ?",
    "reponse": "On teste en priorité ce qui coûte cher s'il casse : paiement, authentification, calculs métier critiques, données sensibles. Le périmètre est un arbitrage risque/effort, pas « tout tester ».",
    "vigilance": "Point checklist : lien tests ↔ risques métier. Cherche la capacité à prioriser."
  },
  {
    "num": 64,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Tests",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Comment testez-vous la sécurité de votre application ?",
    "reponse": "Tests des contrôles d'accès (routes protégées, IDOR), tentatives d'injection, validation des entrées, tests d'authentification/autorisation, analyse de dépendances (npm audit, Dependabot), éventuellement scan OWASP ZAP.",
    "vigilance": "Lien direct avec l'OWASP et le fil rouge sécurité."
  },
  {
    "num": 65,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Tests",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Qu'est-ce que le TDD (Test Driven Development) ?",
    "reponse": "Écrire le test AVANT le code : Red (test qui échoue) → Green (code minimal qui passe) → Refactor. Guide la conception et garantit la couverture.",
    "vigilance": "Question bonus. Ne pas pénaliser s'ils ne l'ont pas pratiqué, mais valoriser s'ils le connaissent."
  },
  {
    "num": 66,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Documentation & déploiement",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Décrivez votre procédure de déploiement, étape par étape.",
    "reponse": "Du push au serveur : build, tests, packaging (image Docker), publication, mise en ligne, vérification. Idéalement automatisé via CI/CD. Documentation de déploiement à l'appui.",
    "vigilance": "Vérifier que le déploiement est reproductible et documenté (point checklist Démo 4)."
  },
  {
    "num": 67,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Documentation & déploiement",
    "demo": "Optionnel",
    "demoKey": "optionnel",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Avez-vous prévu des procédures de sauvegarde et de restauration ?",
    "reponse": "Sauvegardes régulières et automatisées de la BDD, stockage sécurisé/externalisé, test de restauration (une sauvegarde jamais testée n'existe pas). Politique de rétention.",
    "vigilance": "Optionnel mais valorisant. Insister sur le test de restauration."
  },
  {
    "num": 68,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Documentation & déploiement",
    "demo": "Optionnel",
    "demoKey": "optionnel",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Avez-vous une documentation utilisateur (FAQ, guide) ?",
    "reponse": "Guide d'utilisation, FAQ, aide contextuelle destinée aux utilisateurs finaux, distincte de la doc technique.",
    "vigilance": "Optionnel dans la checklist. Bonus de complétude."
  },
  {
    "num": 69,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Démarche DevOps",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce que le CI/CD ? Différence entre CI et CD ?",
    "reponse": "CI (Intégration Continue) : à chaque push, build + tests automatiques pour détecter les régressions tôt. CD (Déploiement/Livraison Continue) : automatisation de la mise en production/livraison après validation.",
    "vigilance": "Question quasi certaine. Faire décrire LEUR pipeline (GitHub Actions, GitLab CI…)."
  },
  {
    "num": 70,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Démarche DevOps",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Décrivez votre pipeline CI/CD. Que se passe-t-il concrètement à chaque push ?",
    "reponse": "Ex : déclenchement sur push/PR → install dépendances → lint → tests → build image → (si branche main) déploiement. Fichier workflow versionné.",
    "vigilance": "Point checklist : lancer les tests à chaque push. Vérifier que le pipeline existe vraiment (captures/logs)."
  },
  {
    "num": 71,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Démarche DevOps",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Qu'est-ce que Dependabot et à quoi sert l'automatisation des dépendances ?",
    "reponse": "Outil qui surveille les dépendances et propose des mises à jour (notamment de sécurité) via des PR automatiques. Réduit la dette et les vulnérabilités connues.",
    "vigilance": "Cité explicitement dans la checklist. Lien avec la sécurité de la supply chain."
  },
  {
    "num": 72,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Démarche DevOps",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce que le monitoring et l'alerting ? Avez-vous mis quelque chose en place ?",
    "reponse": "Surveillance de l'état de l'app (disponibilité, erreurs, performance, logs) et alertes automatiques en cas d'anomalie. Outils : logs, uptime monitoring, Sentry, Grafana…",
    "vigilance": "Même une solution simple (logs + alerte mail) compte. Cherche la conscience de l'exploitation."
  },
  {
    "num": 73,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Démarche DevOps",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment gérez-vous vos versions et vos releases ?",
    "reponse": "Versioning sémantique (MAJEUR.MINEUR.CORRECTIF), tags Git, changelog, releases GitHub. Une montée de version reflète l'ampleur des changements.",
    "vigilance": "Relance : que signifie passer de 1.4.2 à 2.0.0 ? (breaking change)."
  },
  {
    "num": 74,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Démarche DevOps",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Comment sécurisez-vous votre pipeline de déploiement ?",
    "reponse": "Secrets stockés dans le gestionnaire de secrets de la CI (jamais en clair), permissions minimales des tokens, contrôle des accès au repo, scan de vulnérabilités, protection de la branche main (revue obligatoire).",
    "vigilance": "Point checklist explicite. Souvent oublié → bon discriminant."
  },
  {
    "num": 75,
    "bloc": "Bloc 3 — Déploiement sécurisé",
    "categorie": "Démarche DevOps",
    "demo": "Démo 4",
    "demoKey": "demo4",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Qu'est-ce qu'un rollback ? Comment revenez-vous en arrière après un déploiement raté ?",
    "reponse": "Rollback = revenir à la version stable précédente rapidement. Moyens : redéployer l'image/tag précédent, versioning, sauvegardes. L'objectif : minimiser le temps d'indisponibilité.",
    "vigilance": "Lien avec la gestion d'incident en production (compétence transversale RNCP)."
  },
  {
    "num": 76,
    "bloc": "Transversal",
    "categorie": "Qualité & sécurité",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Citez plusieurs vulnérabilités de l'OWASP Top 10 et dites comment vous vous en protégez.",
    "reponse": "Ex : Broken Access Control (contrôle des droits), Injection (requêtes paramétrées), Cryptographic Failures (hachage/HTTPS), XSS, mauvaise config de sécurité, composants vulnérables (Dependabot), SSRF. Associer chaque risque à une parade.",
    "vigilance": "Attendu explicitement (protection contre les vulnérabilités OWASP). En citer 3-4 avec parade concrète."
  },
  {
    "num": 77,
    "bloc": "Transversal",
    "categorie": "Qualité & sécurité",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Comment respectez-vous les standards de code ? Quels outils ?",
    "reponse": "Linter (ESLint, PHP_CS_Fixer, Pylint), formateur (Prettier), conventions de nommage, revue de code, règles partagées dans le repo, éventuellement pre-commit hooks.",
    "vigilance": "Vérifier que c'est automatisé (CI) et pas juste « on fait attention »."
  },
  {
    "num": 78,
    "bloc": "Transversal",
    "categorie": "Qualité & sécurité",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce que le principe de moindre privilège ?",
    "reponse": "N'accorder à chaque utilisateur/service/compte que les droits strictement nécessaires. Limite l'impact d'une compromission. S'applique à la BDD, au serveur, aux tokens, aux rôles applicatifs.",
    "vigilance": "Fil rouge sécurité. Doit revenir naturellement dans plusieurs réponses."
  },
  {
    "num": 79,
    "bloc": "Transversal",
    "categorie": "Qualité & sécurité",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Qu'est-ce qu'une attaque CSRF et comment la prévenir ?",
    "reponse": "CSRF : forcer l'utilisateur authentifié à exécuter une action à son insu via une requête forgée. Parade : token anti-CSRF, SameSite sur les cookies, vérification de l'origine, éviter les actions sensibles en GET.",
    "vigilance": "Distinguer clairement de la XSS (souvent confondues)."
  },
  {
    "num": 80,
    "bloc": "Transversal",
    "categorie": "Qualité & sécurité",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Qu'est-ce qu'un JWT ? Comment le sécurisez-vous ?",
    "reponse": "JSON Web Token : jeton signé (header.payload.signature) pour l'authentification sans état. Sécurité : signature forte, expiration courte, HTTPS, ne pas stocker d'infos sensibles dans le payload (lisible), stockage prudent côté client, refresh token.",
    "vigilance": "Piège : le payload d'un JWT est encodé, pas chiffré → lisible. Vérifier qu'ils le savent."
  },
  {
    "num": 81,
    "bloc": "Transversal",
    "categorie": "Qualité & sécurité",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce que le CORS et pourquoi ça existe ?",
    "reponse": "Cross-Origin Resource Sharing : mécanisme navigateur qui autorise/restreint les requêtes entre origines différentes. Protège l'utilisateur ; le serveur déclare quelles origines sont autorisées via des en-têtes.",
    "vigilance": "Beaucoup l'ont « désactivé » sans comprendre. Creuser la config réelle."
  },
  {
    "num": 82,
    "bloc": "Transversal",
    "categorie": "Qualité & sécurité",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce qu'un middleware et à quoi vous en servez-vous ?",
    "reponse": "Fonction qui s'intercale dans le traitement d'une requête (auth, logs, validation, gestion d'erreurs) avant d'atteindre le contrôleur. Permet de factoriser des traitements transverses.",
    "vigilance": "Exemple attendu : middleware d'authentification qui protège les routes."
  },
  {
    "num": 83,
    "bloc": "Transversal",
    "categorie": "Qualité & sécurité",
    "demo": "Optionnel",
    "demoKey": "optionnel",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment gérez-vous la journalisation (logs) et l'audit ?",
    "reponse": "Logs structurés par niveaux (info, warning, error), horodatés, sans données sensibles en clair, centralisés, conservés pour l'audit et le diagnostic d'incident. Traçabilité des actions sensibles.",
    "vigilance": "Optionnel mais valorisant. Lien avec la gestion d'incident."
  },
  {
    "num": 84,
    "bloc": "Transversal",
    "categorie": "RGPD",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Quelles mentions légales et obligations RGPD avez-vous mises en place ?",
    "reponse": "Mentions légales, politique de confidentialité, base légale du traitement, consentement (cookies), information sur les droits, minimisation des données, sécurisation, durée de conservation. Le RNCP l'exige explicitement.",
    "vigilance": "Compétence transversale obligatoire. Vérifier que c'est réellement implémenté, pas juste théorique."
  },
  {
    "num": 85,
    "bloc": "Transversal",
    "categorie": "RGPD",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Qu'est-ce qu'une donnée personnelle ? Une donnée sensible ?",
    "reponse": "Donnée personnelle : toute info identifiant directement/indirectement une personne (nom, email, IP…). Donnée sensible : catégorie particulière (santé, origine, opinions, biométrie…) à protection renforcée.",
    "vigilance": "Demander quelles données personnelles leur app manipule et comment elles sont protégées."
  },
  {
    "num": 86,
    "bloc": "Transversal",
    "categorie": "RGPD",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Quels droits le RGPD accorde-t-il aux utilisateurs ? Les avez-vous implémentés ?",
    "reponse": "Droits d'accès, de rectification, d'effacement (« droit à l'oubli »), d'opposition, de portabilité, de limitation. Idéalement des fonctionnalités (ex : suppression de compte) les concrétisent.",
    "vigilance": "Lien avec le hachage/anonymisation et la suppression réelle des données."
  },
  {
    "num": 87,
    "bloc": "Transversal",
    "categorie": "Éco-conception",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment avez-vous pris en compte l'éco-conception dans votre projet ?",
    "reponse": "Optimisation des requêtes/du poids des pages, compression des images, mise en cache, pagination, limitation des appels réseau, code efficient, hébergement raisonné. Réduire l'empreinte sans dégrader le service.",
    "vigilance": "Compétence transversale RNCP. Cherche des exemples CONCRETS, pas un discours général."
  },
  {
    "num": 88,
    "bloc": "Transversal",
    "categorie": "Veille",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Comment organisez-vous votre veille technologique et sécuritaire ?",
    "reponse": "Sources suivies (docs officielles, newsletters, blogs, CVE/bulletins ANSSI, comptes/forums), rythme, méthode de tri et de capitalisation. Un exemple récent d'info intégrée au projet est un plus.",
    "vigilance": "Compétence transversale RNCP. Attendu : une démarche vivante, pas « je regarde parfois »."
  },
  {
    "num": 89,
    "bloc": "Transversal",
    "categorie": "Résolution d'incidents",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Décrivez votre démarche structurée face à un incident en production.",
    "reponse": "Détection → qualification/gravité → isolement/mitigation (rollback si besoin) → diagnostic (logs, reproduction) → correction → test de non-régression → communication → post-mortem pour éviter la récidive.",
    "vigilance": "Compétence transversale RNCP explicite. Un incident réel vécu est très valorisant."
  },
  {
    "num": 90,
    "bloc": "Transversal",
    "categorie": "Anglais",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Can you present your project briefly in English? (résumé du projet en anglais)",
    "reponse": "Résumé attendu en anglais (niveau B1) : quoi, pour qui, technologies, votre rôle. Le dossier doit inclure un résumé en anglais (exigence RNCP).",
    "vigilance": "Niveau visé : B1 en compréhension/expression écrite, A2 à l'oral. Évaluer l'aisance, pas la perfection."
  },
  {
    "num": 91,
    "bloc": "Transversal",
    "categorie": "Anglais",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "In English: can you explain what a REST API is and what it is used for?",
    "reponse": "Réponse courte en anglais expliquant : ressources, verbes HTTP, échange JSON, communication client-serveur. Le questionnaire pro inclut des questions ouvertes en anglais à réponse courte.",
    "vigilance": "Simuler le format réel : documentation technique en anglais + réponse écrite courte en anglais."
  },
  {
    "num": 92,
    "bloc": "Transversal",
    "categorie": "Recul & posture",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Si c'était à refaire, que changeriez-vous dans ce projet ?",
    "reponse": "Attendu : autocritique lucide (choix techniques, organisation, dette technique, tests) + ce qu'ils ont appris. Montre la maturité professionnelle.",
    "vigilance": "Une réponse « rien, tout était parfait » est un mauvais signal. On cherche du recul."
  },
  {
    "num": 93,
    "bloc": "Transversal",
    "categorie": "Recul & posture",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Quelle a été votre plus grosse difficulté technique et comment l'avez-vous résolue ?",
    "reponse": "Récit structuré : problème, pistes explorées, démarche de résolution, solution, apprentissage. Démontre la démarche structurée de résolution de problème (compétence RNCP).",
    "vigilance": "Écouter la MÉTHODE de résolution, pas seulement le résultat."
  },
  {
    "num": 94,
    "bloc": "Transversal",
    "categorie": "Recul & posture",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Quelle fonctionnalité vous a demandé le plus de travail et de quoi êtes-vous le plus fier ?",
    "reponse": "Le candidat doit pouvoir expliquer en profondeur une fonctionnalité qu'il maîtrise vraiment, du besoin au code.",
    "vigilance": "Idéal pour vérifier qu'il a bien codé lui-même. Creuser techniquement."
  },
  {
    "num": 95,
    "bloc": "Transversal",
    "categorie": "Recul & posture",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Comment s'est passée la collaboration en équipe ? Comment avez-vous géré les désaccords / conflits Git ?",
    "reponse": "Communication (Slack, Notion, daily), répartition des tâches, revues de code, résolution de conflits Git (merge), gestion des désaccords par la discussion technique.",
    "vigilance": "Compétence de gestion de projet. Sonder l'apport personnel réel dans un projet d'équipe."
  },
  {
    "num": 96,
    "bloc": "Transversal",
    "categorie": "Recul & posture",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Votre application est-elle capable de monter en charge ? Comment géreriez-vous 10x plus d'utilisateurs ?",
    "reponse": "Pistes : cache, index BDD, pagination, optimisation des requêtes, scalabilité horizontale, load balancing, files d'attente, CDN. Distinguer ce qui est fait de ce qui serait à faire.",
    "vigilance": "Question de recul architectural. Une réponse honnête « voici mes pistes » est acceptable."
  },
  {
    "num": 97,
    "bloc": "Transversal",
    "categorie": "Recul & posture",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment garantissez-vous la qualité globale de votre projet ?",
    "reponse": "Combinaison : standards de code + linter, tests, revues de code, CI/CD, documentation, gestion des erreurs, sécurité. La qualité est un ensemble de pratiques, pas un acte isolé.",
    "vigilance": "Vérifier la cohérence avec tout ce qui a été dit avant."
  },
  {
    "num": 98,
    "bloc": "Transversal",
    "categorie": "Recul & posture",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Qu'est-ce que les principes SOLID, DRY et KISS ? Donnez un exemple.",
    "reponse": "DRY : ne pas se répéter (factoriser). KISS : faire simple. SOLID : 5 principes de conception objet (Single responsibility, Open/closed, Liskov, Interface segregation, Dependency inversion). Illustrer par le code.",
    "vigilance": "Ne pas exiger les 5 SOLID par cœur ; valoriser une vraie compréhension d'au moins un."
  },
  {
    "num": 99,
    "bloc": "Transversal",
    "categorie": "Recul & posture",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment gérez-vous la pagination et les grandes quantités de données côté API ?",
    "reponse": "Pagination (limit/offset ou curseur), filtres, tri côté serveur, chargement à la demande. Évite de tout renvoyer d'un coup (perf, mémoire, éco-conception).",
    "vigilance": "Lien avec performance, N+1 et éco-conception."
  },
  {
    "num": 100,
    "bloc": "Transversal",
    "categorie": "Recul & posture",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Intermédiaire",
    "niveauKey": "intermediaire",
    "question": "Comment gérez-vous la session / l'authentification côté client (cookies, tokens) ?",
    "reponse": "Session serveur + cookie, ou token (JWT) stocké côté client. Cookies HttpOnly/Secure/SameSite pour limiter le vol. Expliquer le choix et ses implications de sécurité.",
    "vigilance": "Relance : où stockez-vous le token et pourquoi (localStorage vs cookie HttpOnly) ?"
  },
  {
    "num": 101,
    "bloc": "Transversal",
    "categorie": "Recul & posture",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Avancé",
    "niveauKey": "avance",
    "question": "Comment gérez-vous les migrations de base de données au fil des évolutions ?",
    "reponse": "Fichiers de migration versionnés (via l'ORM/outil dédié), appliqués de façon reproductible sur chaque environnement, réversibles si possible. Évite les modifications manuelles non tracées.",
    "vigilance": "Lien avec le déploiement et la reproductibilité des environnements."
  },
  {
    "num": 102,
    "bloc": "Transversal",
    "categorie": "Recul & posture",
    "demo": "Dossier projet",
    "demoKey": "dossier",
    "niveau": "Fondamental",
    "niveauKey": "fondamental",
    "question": "Présentez votre projet en 2 minutes : le contexte, le problème résolu, votre rôle.",
    "reponse": "Pitch clair et structuré : contexte/client, problème, solution, stack, périmètre personnel, résultat. Sert de fil conducteur à l'entretien.",
    "vigilance": "Premier contact de l'oral. Évaluer la clarté et la capacité de synthèse (le dossier fait 40-60 pages max)."
  }
];
